import cds from '@sap/cds'
import { randomUUID } from 'node:crypto'
import { Orders as PortalOrders, SupplierResponseDeliveries, Suppliers } from '#cds-models/pih/portal'

/**
 * Phase 4.4 — the supplier-facing handler.
 *
 * Two responsibilities, kept apart on purpose.
 *
 * Reads are generated by CAP and constrained by a `before` hook that narrows
 * every query to the signed-in supplier's own rows. Decisions are explicit
 * actions with their own handler; nothing here lets a caller write `status`,
 * `rejectionReason` or `responseVersion` directly, because those are outcomes of
 * a decision rather than fields.
 *
 * Every decision writes the order and its pending outbound response in the same
 * request transaction. Nothing is ever sent to SAP — that is Phase 5.
 */
export default class SupplierService extends cds.ApplicationService {

  init(): Promise<void> {
    // Row-level isolation, applied once, before anything reads.
    this.before('READ', 'Orders', req => this.scopeOrders(req as any))
    this.before('READ', 'OrderItems', req => this.scopeItems(req as any))

    this.on('accept', 'Orders', req => this.decide(req as any, 'ACCEPTED'))
    this.on('reject', 'Orders', req => this.decide(req as any, 'REJECTED'))
    this.on('updateEstimatedDeliveryDate', 'Orders', req => this.decide(req as any, 'DATE_UPDATE'))

    return super.init()
  }

  // ---------------------------------------------------------------- identity

  /**
   * The supplier behind this request.
   *
   * Taken from the authenticated user's attributes, never from the payload or a
   * query parameter: ARCHITECTURE.md requires "authenticated user attributes or
   * an explicit local mock-user mapping, never a trusted supplier code supplied
   * by the browser". Locally that mapping lives in `.cdsrc.json` mocked users.
   */
  private async supplierOf(req: any) {
    const code = req.user?.attr?.supplier

    if (!code) {
      this.refuse(
        req, 403, 'NO_SUPPLIER_IDENTITY',
        'The authenticated user carries no supplier attribute, so no supplier scope can be established.'
      )
    }

    const supplier = await SELECT.one
      .from(Suppliers)
      .columns('ID', 'supplierCode', 'active')
      .where({ supplierCode: code })

    if (!supplier || supplier.active === false) {
      this.refuse(
        req, 403, 'UNKNOWN_SUPPLIER_IDENTITY',
        `The authenticated user maps to supplier "${code}", which is not an active supplier in this portal.`
      )
    }

    return supplier!
  }

  // ------------------------------------------------------------------- reads

  /** Phase 4.5 list contract: `?limit=` (default 20, server maximum 100) and `?offset=`. */
  private static readonly DEFAULT_PAGE = 20
  private static readonly MAX_PAGE = 100

  /**
   * Bounds the order list.
   *
   * API_CONTRACTS.md requires that "lists need bounded pagination" and asks for
   * explicit query parameters "rather than assuming OData query syntax on REST",
   * so the contract is `limit` and `offset` rather than `$top` and `$skip` —
   * neither of which this adapter honoured anyway.
   *
   * A malformed value is a 400 rather than a silent fallback, because a client
   * that asked for something specific should be told it was not understood. An
   * oversized `limit` is clamped to the maximum instead: the request is
   * meaningful, just larger than the portal will serve.
   *
   * Only the collection is paged. A single order read needs no bound, and items
   * are already bounded — ingestion refuses a delivery of more than 100 lines —
   * so paging the detail view would risk truncating an order for no gain.
   */
  private applyPaging(req: any) {
    if (req.query?.SELECT?.one) return

    const params = req.http?.req?.query ?? {}
    const limit = this.positiveInteger(req, params.limit, SupplierService.DEFAULT_PAGE, 'limit')
    const offset = this.positiveInteger(req, params.offset, 0, 'offset')

    req.query.limit(Math.min(limit, SupplierService.MAX_PAGE), offset)
  }

  private positiveInteger(req: any, raw: unknown, fallback: number, name: string) {
    if (raw === undefined) return fallback

    const value = Number(raw)
    if (!Number.isInteger(value) || value < 0) {
      this.refuse(
        req, 400, 'INVALID_PAGINATION',
        `${name} must be a non-negative integer; received "${raw}".`
      )
    }
    return value
  }


  /**
   * Narrows a read to the caller's own rows.
   *
   * The filter is added to the query the framework is about to run, so it
   * applies to the collection, to a single order addressed by key, and to an
   * `$expand`. A supplier asking for another supplier's order id gets an empty
   * result rather than a refusal, which is the "scoped not-found response; no
   * fields disclosed" outcome the design acceptance cases describe.
   */
  private async scopeOrders(req: any) {
    const supplier = await this.supplierOf(req)
    req.query.where({ supplierCode: supplier.supplierCode })
    this.applyPaging(req)
  }

  /**
   * The same narrowing for items, expressed over the item projection's own
   * elements: an item is visible only if its parent order belongs to the caller.
   */
  private async scopeItems(req: any) {
    const supplier = await this.supplierOf(req)
    req.query.where({
      portalOrderId: { in: SELECT('ID').from(PortalOrders).where({ supplier_ID: supplier.ID }) }
    })
  }

  // --------------------------------------------------------------- decisions

  private async decide(req: any, kind: 'ACCEPTED' | 'REJECTED' | 'DATE_UPDATE') {
    const supplier = await this.supplierOf(req)
    const { responseId, expectedResponseVersion, estimatedDeliveryDate, reason } = req.data

    if (!responseId || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(responseId)) {
      this.refuse(req, 400, 'MISSING_RESPONSE_ID', 'responseId is required and must be a canonical UUID.')
    }
    if (!Number.isInteger(expectedResponseVersion) || expectedResponseVersion < 0) {
      this.refuse(
        req, 400, 'MISSING_VERSION_PRECONDITION',
        'expectedResponseVersion is required and must be a non-negative integer.'
      )
    }

    const portalOrderId = req.params?.[0]?.portalOrderId ?? req.params?.[0]
    const order = await SELECT.one
      .from(PortalOrders)
      .where({ ID: portalOrderId, supplier_ID: supplier.ID })

    // Scoped not-found: another supplier's order is indistinguishable from one
    // that does not exist, so ownership is never disclosed by the error.
    if (!order) {
      this.refuse(
        req, 404, 'ORDER_NOT_FOUND',
        `No order ${portalOrderId} exists for this supplier.`
      )
    }

    // Replay detection runs before the version precondition and before date
    // validation, because "deduplication runs before current-date validation"
    // and a replay must succeed "even if its original version is now stale".
    const previous = await SELECT.one
      .from(SupplierResponseDeliveries)
      .where({ responseId })

    if (previous) {
      return this.answerReplay(req, previous, order!, kind, estimatedDeliveryDate, reason)
    }

    if (order!.responseVersion !== expectedResponseVersion) {
      this.refuse(
        req, 409, 'STALE_RESPONSE_VERSION',
        `expectedResponseVersion ${expectedResponseVersion} does not match the order's current responseVersion ${order!.responseVersion}. Reread the order and reassess; a newer decision must not be overwritten.`
      )
    }

    const decision = this.validateTransition(req, order!, kind, estimatedDeliveryDate, reason)
    const respondedAt = new Date().toISOString()
    const version = (order!.responseVersion ?? 0) + 1

    await this.persist(order!, decision, version, responseId, respondedAt)

    return this.decisionResult(order!, decision, version, respondedAt)
  }

  /**
   * Lifecycle and content rules for one command.
   *
   * These are portal rules about a supplier's own response. They do not restate
   * anything RAP decides: SAP's `submit`, `approve` and `cancel` are a different
   * lifecycle on a different system, and the portal only governs what a supplier
   * may answer about a snapshot it was sent.
   */
  private validateTransition(
    req: any,
    order: any,
    kind: 'ACCEPTED' | 'REJECTED' | 'DATE_UPDATE',
    estimatedDeliveryDate?: string,
    reason?: string
  ) {
    if (kind === 'DATE_UPDATE') {
      if (order.status !== 'ACCEPTED') {
        this.refuse(
          req, 409, 'INVALID_STATE_FOR_DATE_UPDATE',
          `A delivery date can only be updated on an accepted order; this order is ${order.status}.`
        )
      }
      this.requireFutureDate(req, estimatedDeliveryDate)

      return {
        status: 'ACCEPTED' as const,
        estimatedDeliveryDate: estimatedDeliveryDate!,
        rejectionReason: null
      }
    }

    if (order.status !== 'RECEIVED') {
      this.refuse(
        req, 409, 'INVALID_STATE_FOR_DECISION',
        `Only a received order can be accepted or rejected; this order is already ${order.status}.`
      )
    }

    if (kind === 'REJECTED') {
      const text = typeof reason === 'string' ? reason.trim() : ''
      if (!text) {
        this.refuse(req, 400, 'MISSING_REJECTION_REASON', 'A rejection requires a reason.')
      }
      if (text.length > 255) {
        this.refuse(req, 400, 'REJECTION_REASON_TOO_LONG', 'A rejection reason may be at most 255 characters.')
      }

      // Rejection forbids a delivery date, so none is stored.
      return { status: 'REJECTED' as const, estimatedDeliveryDate: null, rejectionReason: text }
    }

    if (estimatedDeliveryDate != null) this.requireFutureDate(req, estimatedDeliveryDate)

    // An omitted date on acceptance means unknown, not today.
    return {
      status: 'ACCEPTED' as const,
      estimatedDeliveryDate: estimatedDeliveryDate ?? null,
      rejectionReason: null
    }
  }

  /**
   * "A newly supplied date cannot be earlier than the date portion of request
   * receipt in UTC." Compared as calendar dates, so a date of today passes.
   */
  private requireFutureDate(req: any, value?: string) {
    if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) {
      this.refuse(
        req, 400, 'INVALID_DELIVERY_DATE',
        `estimatedDeliveryDate "${value}" must be a calendar date formatted YYYY-MM-DD.`
      )
    }
    if (Number.isNaN(Date.parse(`${value}T00:00:00Z`))) {
      this.refuse(req, 400, 'INVALID_DELIVERY_DATE', `estimatedDeliveryDate "${value}" is not a real date.`)
    }

    const today = new Date().toISOString().slice(0, 10)
    if (value! < today) {
      this.refuse(
        req, 400, 'DELIVERY_DATE_IN_PAST',
        `estimatedDeliveryDate ${value} is earlier than the UTC date of this request, ${today}.`
      )
    }
  }

  /**
   * The decision and its pending outbound response, in one transaction.
   *
   * CAP runs both statements inside the request's transaction, so an order can
   * never end up ACCEPTED with no pending response, nor keep a pending response
   * while still RECEIVED. Either both rows land or neither does.
   */
  private async persist(
    order: any,
    decision: { status: 'ACCEPTED' | 'REJECTED'; estimatedDeliveryDate: string | null; rejectionReason: string | null },
    version: number,
    responseId: string,
    respondedAt: string
  ) {
    await UPDATE(PortalOrders)
      .set({
        status: decision.status,
        estimatedDeliveryDate: decision.estimatedDeliveryDate,
        rejectionReason: decision.rejectionReason,
        responseVersion: version,
        modifiedAt: respondedAt
      } as any)
      .where({ ID: order.ID })

    await INSERT.into(SupplierResponseDeliveries).entries({
      ID: cds.utils.uuid(),
      responseId,
      order_ID: order.ID,
      version,
      decision: decision.status,
      estimatedDeliveryDate: decision.estimatedDeliveryDate,
      reason: decision.rejectionReason,
      respondedAt,
      state: 'PENDING'
    } as any)
  }

  /**
   * A replayed `responseId`.
   *
   * Identical content is a no-op that returns the committed decision; the
   * opposite decision under the same identity is a conflict, and must not
   * change anything.
   */
  private answerReplay(
    req: any,
    previous: any,
    order: any,
    kind: 'ACCEPTED' | 'REJECTED' | 'DATE_UPDATE',
    estimatedDeliveryDate?: string,
    reason?: string
  ) {
    const expected = kind === 'DATE_UPDATE' ? 'ACCEPTED' : kind
    const sameDate = (previous.estimatedDeliveryDate ?? null) === (estimatedDeliveryDate ?? null)
    const sameReason = (previous.reason ?? null) === (typeof reason === 'string' ? reason.trim() : reason ?? null)

    if (previous.decision !== expected || previous.order_ID !== order.ID || !sameDate || !sameReason) {
      this.refuse(
        req, 409, 'RESPONSE_PAYLOAD_CONFLICT',
        `responseId ${previous.responseId} was already recorded with different content. The stored decision is unchanged; use a new responseId for a different response.`
      )
    }

    return this.decisionResult(
      order,
      {
        status: previous.decision,
        estimatedDeliveryDate: previous.estimatedDeliveryDate ?? null,
        rejectionReason: previous.reason ?? null
      },
      previous.version,
      previous.respondedAt
    )
  }

  /** The supplier-facing result defined in API_CONTRACTS.md. */
  private decisionResult(
    order: any,
    decision: { status: string; estimatedDeliveryDate: string | null; rejectionReason: string | null },
    version: number,
    respondedAt: string
  ) {
    return {
      portalOrderId: order.ID,
      externalOrderNumber: order.externalOrderNumber,
      status: decision.status,
      responseVersion: version,
      estimatedDeliveryDate: decision.estimatedDeliveryDate,
      rejectionReason: decision.rejectionReason,
      respondedAt,
      // Never a claim that SAP has been updated; no sender exists before Phase 5.
      responseDeliveryStatus: 'PENDING'
    }
  }

  /** The error envelope defined in API_CONTRACTS.md. */
  private refuse(req: any, status: number, code: string, message: string): never {
    const correlationId = req.headers?.['x-correlation-id'] ?? randomUUID()
    req.http?.res?.setHeader?.('X-Correlation-ID', correlationId)
    req.reject({ status, code, message, correlationId, retryable: false })
    throw new Error('unreachable')
  }
}
